Inline pint and phpcs

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -60,7 +60,64 @@ jobs:
         uses: sudo-bot/action-scrutinizer@latest
         with:
           cli-args: "--format=php-clover tests/reports/clover.xml --revision=${{ github.event.pull_request.head.sha || github.sha }}"
+  phpcs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: 8.4
+          tools: cs2pr, phpcs
+
+      - name: Setup phpcs config
+        run: |
+          {
+            echo '<?xml version="1.0"?>'
+            echo '<ruleset name="DD Detection Standard">'
+            echo '<description>Detects and fails for dd found in code.</description>'
+            echo '<arg name="colors"/>'
+            echo '<arg value="n"/>'
+            echo '<rule ref="Generic.PHP.ForbiddenFunctions">'
+            echo '<properties>'
+            echo '<property name="forbiddenFunctions" type="array">'
+            echo '<element key="dd" value="null"/>'
+            echo '</property>'
+            echo '</properties>'
+            echo '</rule>'
+            echo '</ruleset>'
+          } > custom_phpcs_style.xml
+        
+      - name: Run PHP CS Fixer
+        run: |
+          (phpcs --standard=custom_phpcs_style.xml --report=checkstyle ${{ inputs.dir }} | cs2pr) || true
+          phpcs --standard=custom_phpcs_style.xml ${{ inputs.dir }}
   pint:
-    uses: intouchinsight/github-workflows/.github/workflows/laravel-pint.yml@main
-    with:
-      php_version: '8.3'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Find pint version
+        id: find_pint_version
+        run: |
+          PINT_VERSION='v1.13'
+          echo "Attempting to load pint version from composer.lock"
+          if [ -f composer.lock ]; then
+            PINT_VERSION=$(jq '.["packages-dev"][] | select(.name == "laravel/pint") | .version' composer.lock)
+          fi
+          echo "Found pint version: $PINT_VERSION"
+          echo "PINT_VERSION=$PINT_VERSION" >> $GITHUB_OUTPUT
+
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: 8.4
+          tools: cs2pr, pint:${{ steps.find_pint_version.outputs.PINT_VERSION }}
+  
+      - name: Run pint 
+        run: |
+          (pint --test --format=checkstyle | cs2pr) || true
+          pint --test -v --ansi
